
logging:
  level:
    com:
      boot: warn
  file:
     name: "system.log"

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        watch-delay: 5000
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
  thymeleaf:
    cache: false
  jackson:
    date-format: "yyyy-MM-dd"
    time-zone: "GMT+8"
  profiles:
    include: jdbc
  application:
    name: Iacaa20Server
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 9999


# ====================MybatisPlus====================
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/dao/*Mapper.xml
  # 如果是放在resource目录 classpath:/dao/*Mapper.xml
  mapper-locations: classpath:/xml/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.pzhu.iacaa2_0.**.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #      field-strategy: 2
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    database-id: mysql
com:
  gapache:
    security:
      register-remote: true
      update-resources: true
      client-id: Iacaa20Server
    vertx:
      settings:
        cluster: false


